spring.application.name=cms

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#swagger??
springdoc.override-with-generic-response=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true